### ISSUE TITLE
MatchSamples should generate a new file with case/control info

### ISSUE THREAD

**Issue by kbeutel** [PankratzLab/MatchSamples#7]
From issues notes:
MatchSamples should generate a new file with three columns (ID and whether they were selected as a case or a control, with the third column being the case/control that they were matched to) so that we can merge this directly into a phenotype file

**Comment by npankrat** [comment]
Correction: for the rows with case IDs, the third column should also be the case ID (i.e., columns 1 and 3 would be the same)

**Comment by jameeters** [comment]
Here's the changes I've made so far for this: 
https://github.com/PankratzLab/MatchSamples/compare/case_control_file
https://github.com/PankratzLab/kd-match/compare/sample_status_output
