### ISSUE TITLE
Feature request: Re-implement the -eval methods

### ISSUE THREAD

**Issue by kbeutel** [PankratzLab/MatchSamples#9]
From the issues doc:

Intended behavior is to read in the matches just made and make a table where:
- [ ] Each row is a different matching variable with the average value for the cases and the average value for the controls next to each other. If the variable is binary, then we’ll have the percent in cases next to percent in controls and an extra column with the % concordance.
- [ ] For all columns, we’ll want a p-value from a univariate logistic regression model with the case-control status as the outcome and the variable in question as the predictor.
- [ ] Also compute a p-value from a multiple logistic regression with all matching variables present in the model.
- [ ] Investigate for performance on something like UKB with lots of samples. A glm in R can take seconds whereas our Java methods in Genvisis can take a long time. One of our stats libraries might be more performant. John Lane can pair-program and mentor on this item

**Comment by jameeters** [comment]
https://github.com/PankratzLab/MatchSamples/compare/reimplement_eval_stuff
